In [2]:
import pandas as pd

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
def print_array(A):
    for i in range(len(A)):
        print(A[i], end = " ")

In [17]:
def print_line(A):
    for i in range(len(A)):
        if A[i] == 0 :
            print(" ", end = " ")
        else:
            print("*", end = " ")

In [18]:
def print_image(I):
    for i in range(len(I)):
        print_line(I[i])
        print("\n")

# First simple Demo of Tensorflow

In [4]:
# Import of data set!
X_raw = np.array([2013, 2014, 2015, 2016, 2017, 2018, 2019])
y_raw = np.array([12000, 14000, 15000, 16500, 17500, 18900, 20000])
X = (X_raw - X_raw.min()) / (X_raw.max() - X_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

In [5]:
tf.enable_eager_execution()

# Using tensorflow to convert the data set
X = tf.constant(X, dtype=tf.float32)
y = tf.constant(y, dtype=tf.float32)

In [5]:
tf.enable_eager_execution()
# Setting the variables
a = tf.get_variable('a', dtype=tf.float32, shape=[], initializer=tf.zeros_initializer)
b = tf.get_variable('b', dtype=tf.float32, shape=[], initializer=tf.zeros_initializer)
variables = [a, b]

num_epoch = 1000
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-3)
for e in range(num_epoch):
    with tf.GradientTape() as tape:
        y_pred = a * X + b
        loss = 0.5 * tf.reduce_sum(tf.square(y_pred - y))
    grads = tape.gradient(loss, variables)

    optimizer.apply_gradients(grads_and_vars=zip(grads, variables))
    print("loss: ",loss.numpy())

loss:  1.3680469
loss:  1.3472793
loss:  1.3268763
loss:  1.3068311
loss:  1.2871377
loss:  1.2677896
loss:  1.248781
loss:  1.2301056
loss:  1.2117575
loss:  1.1937311
loss:  1.1760204
loss:  1.1586199
loss:  1.1415243
loss:  1.1247281
loss:  1.108226
loss:  1.0920125
loss:  1.0760827
loss:  1.0604317
loss:  1.0450543
loss:  1.029946
loss:  1.0151016
loss:  1.0005165
loss:  0.9861864
loss:  0.97210664
loss:  0.9582726
loss:  0.9446801
loss:  0.93132484
loss:  0.91820264
loss:  0.90530914
loss:  0.8926405
loss:  0.88019276
loss:  0.86796194
loss:  0.8559443
loss:  0.84413576
loss:  0.8325329
loss:  0.8211318
loss:  0.80992925
loss:  0.79892147
loss:  0.78810513
loss:  0.77747667
loss:  0.767033
loss:  0.75677055
loss:  0.7466863
loss:  0.7367771
loss:  0.7270399
loss:  0.7174715
loss:  0.70806885
loss:  0.69882923
loss:  0.68974966
loss:  0.6808272
loss:  0.67205924
loss:  0.6634429
loss:  0.6549756
loss:  0.6466547
loss:  0.6384775
loss:  0.6304415
loss:  0.6225442
loss:  0.61478317
l

loss:  0.10602562
loss:  0.105898805
loss:  0.105772145
loss:  0.10564564
loss:  0.105519325
loss:  0.10539317
loss:  0.10526717
loss:  0.105141334
loss:  0.10501566
loss:  0.10489015
loss:  0.104764804
loss:  0.10463959
loss:  0.104514584
loss:  0.10438971
loss:  0.104265004
loss:  0.10414046
loss:  0.10401608
loss:  0.10389185
loss:  0.10376779
loss:  0.10364388
loss:  0.103520125
loss:  0.10339655
loss:  0.103273116
loss:  0.10314983
loss:  0.10302673
loss:  0.10290378
loss:  0.10278097
loss:  0.102658324
loss:  0.102535814
loss:  0.102413505
loss:  0.102291316
loss:  0.10216929
loss:  0.102047436
loss:  0.10192573
loss:  0.10180417
loss:  0.10168277
loss:  0.1015615
loss:  0.101440415
loss:  0.10131946
loss:  0.101198666
loss:  0.10107805
loss:  0.10095755
loss:  0.1008372
loss:  0.10071702
loss:  0.100597
loss:  0.10047712
loss:  0.100357406
loss:  0.1002378
loss:  0.10011838
loss:  0.09999912
loss:  0.09987997
loss:  0.099760994
loss:  0.09964219
loss:  0.0995235
loss:  0.0994049

# Getting Started with Models

In [6]:
X = tf.constant([[1.,2.,3.],[4.,5.,6.]])
y = tf.constant([[10.],[20.]])

In [7]:
class Linear(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(units=1, kernel_initializer=tf.zeros_initializer(),
                                           bias_initializer=tf.zeros_initializer())
    def call(self, input):
        output = self.dense(input)
        return output

In [8]:
model = Linear()
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
for i in range(1000):
    with tf.GradientTape() as tape:
        y_pred = model(X) # 调用模型
        loss = tf.reduce_mean(tf.square(y_pred - y))
    grads = tape.gradient(loss, model.variables)
    optimizer.apply_gradients(grads_and_vars=zip(grads, model.variables))
    print(model.variables[0].numpy(),model.variables[1].numpy() )

[[0.9      ]
 [1.1999999]
 [1.5      ]] [0.29999998]
[[0.96300006]
 [1.2930001 ]
 [1.6230001 ]] [0.33]
[[0.96011996]
 [1.29879   ]
 [1.63746   ]] [0.33867]
[[0.952118 ]
 [1.2977219]
 [1.6433258]] [0.34560385]
[[0.94378096]
 [1.296127  ]
 [1.6484731 ]] [0.35234603]
[[0.93548524]
 [1.2945038 ]
 [1.6535225 ]] [0.3590186]
[[0.9272599]
 [1.2928916]
 [1.6585233]] [0.36563167]
[[0.9191067]
 [1.2912933]
 [1.6634798]] [0.37218654]
[[0.9110252]
 [1.289709 ]
 [1.6683928]] [0.37868378]
[[0.9030147]
 [1.2881386]
 [1.6732625]] [0.38512385]
[[0.89507467]
 [1.286582  ]
 [1.6780893 ]] [0.3915073]
[[0.8872044]
 [1.2850391]
 [1.6828736]] [0.39783463]
[[0.8794035]
 [1.2835099]
 [1.6876161]] [0.40410635]
[[0.8716711]
 [1.281994 ]
 [1.6923168]] [0.4103229]
[[0.8640067]
 [1.2804915]
 [1.6969762]] [0.4164848]
[[0.85640967]
 [1.2790022 ]
 [1.7015946 ]] [0.42259252]
[[0.84887934]
 [1.2775259 ]
 [1.7061722 ]] [0.42864653]
[[0.84141535]
 [1.2760627 ]
 [1.7107098 ]] [0.43464735]
[[0.8340169]
 [1.2746123]
 [1.71520

[[0.12162551]
 [1.134955  ]
 [2.1482832 ]] [1.01333]
[[0.12055602]
 [1.1347454 ]
 [2.1489332 ]] [1.0141897]
[[0.11949607]
 [1.1345377 ]
 [2.1495776 ]] [1.015042]
[[0.11844545]
 [1.1343318 ]
 [2.1502166 ]] [1.0158867]
[[0.11740396]
 [1.1341276 ]
 [2.1508496 ]] [1.016724]
[[0.11637158]
 [1.1339252 ]
 [2.151477  ]] [1.0175539]
[[0.11534833]
 [1.1337246 ]
 [2.1520991 ]] [1.0183766]
[[0.11433412]
 [1.1335257 ]
 [2.1527157 ]] [1.019192]
[[0.11332881]
 [1.1333287 ]
 [2.1533267 ]] [1.0200002]
[[0.11233237]
 [1.1331334 ]
 [2.1539326 ]] [1.0208013]
[[0.11134467]
 [1.1329398 ]
 [2.1545331 ]] [1.0215954]
[[0.1103656]
 [1.1327479]
 [2.1551282]] [1.0223825]
[[0.10939518]
 [1.1325576 ]
 [2.155718  ]] [1.0231627]
[[0.10843328]
 [1.132369  ]
 [2.156303  ]] [1.023936]
[[0.10747988]
 [1.1321821 ]
 [2.1568825 ]] [1.0247025]
[[0.10653482]
 [1.1319969 ]
 [2.157457  ]] [1.0254623]
[[0.10559802]
 [1.1318132 ]
 [2.1580265 ]] [1.0262153]
[[0.10466962]
 [1.1316313 ]
 [2.158591  ]] [1.0269618]
[[0.10374922]
 [1.1

 [2.2140217 ]] [1.1002669]
[[0.01337021]
 [1.1137327 ]
 [2.2140937 ]] [1.1003623]
[[0.01325268]
 [1.1137097 ]
 [2.2141652 ]] [1.1004568]
[[0.01313613]
 [1.1136868 ]
 [2.214236  ]] [1.1005505]
[[0.01302066]
 [1.1136642 ]
 [2.2143064 ]] [1.1006434]
[[0.01290612]
 [1.1136416 ]
 [2.214376  ]] [1.1007354]
[[0.01279269]
 [1.1136194 ]
 [2.214445  ]] [1.1008266]
[[0.01268015]
 [1.1135973 ]
 [2.2145133 ]] [1.100917]
[[0.01256866]
 [1.1135755 ]
 [2.214581  ]] [1.1010066]
[[0.01245816]
 [1.1135538 ]
 [2.2146482 ]] [1.1010954]
[[0.01234866]
 [1.1135323 ]
 [2.214715  ]] [1.1011835]
[[0.01224008]
 [1.113511  ]
 [2.214781  ]] [1.1012708]
[[0.01213245]
 [1.1134899 ]
 [2.2148464 ]] [1.1013573]
[[0.01202587]
 [1.1134691 ]
 [2.2149115 ]] [1.1014432]
[[0.01192001]
 [1.1134483 ]
 [2.2149756 ]] [1.1015282]
[[0.01181514]
 [1.1134276 ]
 [2.2150393 ]] [1.1016124]
[[0.01171128]
 [1.1134073 ]
 [2.2151024 ]] [1.101696]
[[0.01160834]
 [1.1133871 ]
 [2.2151651 ]] [1.1017789]
[[0.01150626]
 [1.1133671 ]
 [2.2152271 

 [2.2212546e+00]] [1.1098322]
[[1.5773490e-03]
 [1.1114204e+00]
 [2.2212632e+00]] [1.1098434]
[[1.5634159e-03]
 [1.1114175e+00]
 [2.2212715e+00]] [1.1098545]
[[1.5497783e-03]
 [1.1114150e+00]
 [2.2212801e+00]] [1.1098655]
[[1.5361217e-03]
 [1.1114123e+00]
 [2.2212884e+00]] [1.1098765]
[[1.5225986e-03]
 [1.1114097e+00]
 [2.2212965e+00]] [1.1098874]
[[1.5091422e-03]
 [1.1114069e+00]
 [2.2213047e+00]] [1.1098981]
[[1.4959052e-03]
 [1.1114044e+00]
 [2.2213128e+00]] [1.1099088]
[[1.4827255e-03]
 [1.1114018e+00]
 [2.2213206e+00]] [1.1099194]
[[1.4697651e-03]
 [1.1113993e+00]
 [2.2213287e+00]] [1.1099299]
[[1.4567951e-03]
 [1.1113967e+00]
 [2.2213366e+00]] [1.1099403]
[[1.4439683e-03]
 [1.1113942e+00]
 [2.2213445e+00]] [1.1099505]
[[1.4312081e-03]
 [1.1113915e+00]
 [2.2213521e+00]] [1.1099607]
[[1.4186864e-03]
 [1.1113892e+00]
 [2.2213600e+00]] [1.1099708]
[[1.4062219e-03]
 [1.1113868e+00]
 [2.2213676e+00]] [1.1099808]
[[1.3937574e-03]
 [1.1113843e+00]
 [2.2213750e+00]] [1.1099907]
[[1.381445

 [2.2221081e+00]] [1.1109604]
[[1.8628153e-04]
 [1.1111474e+00]
 [2.2221091e+00]] [1.1109617]
[[1.846126e-04]
 [1.111147e+00]
 [2.222110e+00]] [1.110963]
[[1.8300088e-04]
 [1.1111467e+00]
 [2.2221110e+00]] [1.1109643]
[[1.8145594e-04]
 [1.1111465e+00]
 [2.2221122e+00]] [1.1109656]
[[1.7979654e-04]
 [1.1111461e+00]
 [2.2221131e+00]] [1.1109669]
[[1.7820390e-04]
 [1.1111457e+00]
 [2.2221141e+00]] [1.1109682]
[[1.7665896e-04]
 [1.1111455e+00]
 [2.2221150e+00]] [1.1109695]
[[1.7509493e-04]
 [1.1111451e+00]
 [2.2221160e+00]] [1.1109707]
[[1.7352137e-04]
 [1.1111448e+00]
 [2.2221169e+00]] [1.1109719]
[[1.7199549e-04]
 [1.1111444e+00]
 [2.2221179e+00]] [1.1109731]
[[1.7045054e-04]
 [1.1111441e+00]
 [2.2221189e+00]] [1.1109743]
[[1.6904864e-04]
 [1.1111439e+00]
 [2.2221198e+00]] [1.1109755]
[[1.6754183e-04]
 [1.1111436e+00]
 [2.2221208e+00]] [1.1109767]
[[1.6601595e-04]
 [1.1111432e+00]
 [2.2221215e+00]] [1.1109779]
[[1.6455683e-04]
 [1.1111430e+00]
 [2.2221224e+00]] [1.1109791]
[[1.6307863e-0

# MLP for MINIST

In [6]:
mnist = tf.keras.datasets.mnist

In [7]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [8]:
class DataLoader():
    def __init__(self):
        self.train_data = x_train
        self.train_labels = y_train
        self.eval_data = x_test
        self.eval_labels = y_test
    def get_batch(self, batch_size):
        index = np.random.randint(0, np.shape(self.train_data)[0], batch_size)
        return self.train_data[index, :], self.train_labels[index]

In [9]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(units=100, activation=tf.nn.sigmoid)
        self.dense2 = tf.keras.layers.Dense(units=10)
        
    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return x
    
    def predict(self, inputs):
        logits = self(inputs)
        return tf.argmax(logits, axis=-1)

In [11]:
#Hyper Parameters:
num_batches = 1000
batch_size = 50
learning_rate = 0.01

In [12]:
model = MLP()
print("finish model establishing")
data_loader = DataLoader()
print("finish loading data")
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate)

finish model establishing
finish loading data


In [21]:
def check_sample(n):
    print_image(data_loader.train_data[n])
    print(data_loader.train_labels[n])

## Training

In [23]:
for batch_index in range(num_batches):
    X, y = data_loader.get_batch(batch_size)
    with tf.GradientTape() as tape:
        y_logit_pred = model(tf.convert_to_tensor(X, tf.dtype.int32))
        loss = tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_logit_pred)
        print("batch %d: loss %f" % (batch_index, loss.numpy()))
    grads = tape.gradient(loss, model.variables)
    optimizer.apply_gradients(grads_and_vars=zip(grads, model.variables))

AttributeError: module 'tensorflow' has no attribute 'dtype'

In [57]:
model(tf.convert_to_tensor(X, dtype = tf.int32))

ValueError: Invalid dtype tf.uint8